### ISSUE TITLE
memory load data not working with yaml

### ISSUE THREAD

**Issue by Gl4di4torRr** [micro/go-config#100]
I noticed [this](https://github.com/micro/go-config/blob/f4972c5df6170210a3c6a6eec4f3b2228daf1c5f/source/memory/options.go#L29) sets the format to json. Possibly this could cause an issue when the file is in a `yaml` format?

**Comment by asim** [comment]
You could specify the changeset using WithChangeSet otherwise we'd have to change the args passed in or provide a different way to do this.

**Comment by asim** [comment]
WithJSON and WithYAML options have been added here https://github.com/micro/go-micro/commit/082d0b9f05fe8fcb637893c5a9eed29f105e47a5

Go config has now moved to go-micro/config. Please use it there.
