### ISSUE TITLE
why does go-config not support multiple etcd endpoints option?

### ISSUE THREAD

**Issue by outshow** [micro/go-config#103]
Current go-config only supports one etcd endpoin option likes:
`etcd.WithAddress("10.0.0.10:8500")`
but the original etcd client v3 supports:
`type Config struct {
	// Endpoints is a list of URLs.
	Endpoints []string `json:"endpoints"``
go-config is a great project, it will be better if it supports more features.

**Comment by asim** [comment]
Made the fix here https://github.com/micro/go-config/commit/b2c9a63262b3dd666a2dc13249baefdd49067932. Close if satisfied. Thanks.

**Comment by outshow** [comment]
Well done. @asim 👍
