### ISSUE TITLE
go get error. broken dependency

### ISSUE THREAD

**Issue by kobe90s** [micro/go-config#104]
go version: go version go1.12.1 darwin/amd64

go: github.com/testcontainers/testcontainer-go@v0.0.2: parsing go.mod: unexpected module path "github.com/testcontainers/testcontainers-go"
go: error loading module requirements

**Comment by asim** [comment]
go get -u may fail but go get will not

**Comment by kobe90s** [comment]
i have tried both go get and go get -u. both give the same error

**Comment by kobe90s** [comment]
if go module is disabled, go get works ok

**Comment by vadimi** [comment]
I'm getting the same error. It looks like `github.com/testcontainers/testcontainer-go@v0.0.2` does not exist in https://github.com/testcontainers/testcontainers-go/releases. They have `0.0.2` which is not canonical form.

**Comment by noahzaozao** [comment]
I have same issue with go get -v github.com/micro/go-config, and github.com/testcontainers/testcontainer-go@v0.0.2.May be this PR can fix the go get issue #106 ? @asim

**Comment by noahzaozao** [comment]
I've sloved this problem after added these lines in go.mod of my project

```
replace github.com/sourcegraph/go-diff => github.com/sourcegraph/go-diff v0.5.1

replace github.com/golang/lint v0.0.0-20190313153728-d0100b6bd8b3 => golang.org/x/lint v0.0.0-20190409202823-5614ed5bae6fb75893070bdc0996a68765fdd275

replace github.com/testcontainers/testcontainer-go => github.com/testcontainers/testcontainers-go v0.0.0-20181115231424-8e868ca12c0f
```

**Comment by asim** [comment]
Go config has moved to go-micro/config and we've resolved these issues there.
