### ISSUE TITLE
config seems to only merge at root level

### ISSUE THREAD

**Issue by from-nibly** [micro/go-config#18]
I have some config.json file that looks something like this
```JSON
{
  "amqp": {
    "host": "rabbit.platform",
    "port": 80
  },
  "handler": {
    "exchange": "springCloudBus"
  }
}
```

If I define a config object like this
```go
conf := config.NewConfig()

conf.Load(
        file.NewSource(
		file.WithPath("./defaults.json"),
	),
	envvar.NewSource(),
)
```
With an environment variable AMQP_HOST="rabbit.testing.com" and I run.
```go
conf.Get("amqp", "host").String("backup")
```

I still get `"rabbit.platform"`. If I reverse the order I get `"rabbit.testing.com"` but `"amqp.port"` is gone. Does this library do a deep merge or does it just merge the root properties?

**Comment by asim** [comment]
This should merge down. It seems like a bug in processing. Not really clear what's going on.

**Comment by pijalu** [comment]
Bug in mergo
Submitted https://github.com/imdario/mergo/pull/81 for a possible fix

**Comment by asim** [comment]
This issue is now resolved as the PR was merged. Thanks to both.
