### ISSUE TITLE
cant do go get

### ISSUE THREAD

**Issue by k1ng440** [micro/go-config#23]
go get github.com/micro/go-config
# github.com/micro/go-config/reader/json
/mnt/d/Go/src/github.com/micro/go-config/reader/json/json.go:33:22: too many arguments in call to mergo.Map
/mnt/d/Go/src/github.com/micro/go-config/reader/json/json.go:33:38: undefined: mergo.WithOverride

**Comment by asim** [comment]
`go get -u github.com/micro/go-config`
