### ISSUE TITLE
Casting vs Type Assertions

### ISSUE THREAD

**Issue by raizyr** [micro/go-config#26]
Currently the README states that:

> The config.Get method returns a reader.Value which can cast to any type with a fallback value

But it appears that it is only doing type assertions from `go-simplejson` rather than casting, or type conversion.  This can be problematic when for example using the `envvar` source, since all environment variables get parsed as strings.

Given the following environment variables:
```shell
DATABASE_ADDRESS=127.0.0.1
DATABASE_PORT=3306
```
The resulting config becomes:
```json
{
    "database": {
        "address": "127.0.0.1",
        "port": "3306"
    }
}
```
rather than 
```json
{
    "database": {
        "address": "127.0.0.1",
        "port": 3306
    }
}
```

This results in this example always returning the default value and never the value from the environment source.
```go
envvarSource := envvar.NewSource()
conf := config.NewConfig()
conf.Load(envvarSource)

port := config.Get("database", "port").Int(5432) // port is 5432 rather than 3306
```

I see a couple options for handling this, but before I work on a PR for it, I wanted to see which way you'd prefer to go.

1. Add logic to `jsonValue.Type()` methods to attempt casting if the `MustType()` fails.
2. Alternatively
    1. Change the main readme to reflect that it Value does type assertion
    2. Add logic to `envvar.Read()` to try coerce to Int, Bool, Float, or Duration at read time, and update `envvar`'s readme.
3. A third option I've missed 😄

**Comment by asim** [comment]
It would be nice if it did handle this correctly. Not ideal having everything as strings when they come from flags or env vars. I'll have a look into it. It's likely something that needs to occur in the reader at the time the user explicitly makes the choice to make it an int, float, bool, etc.

**Comment by asim** [comment]
We now gracefully attempt to handle string values https://github.com/micro/go-config/commit/8baa25358775de0244578dfee051bfcd01bc9ab2

Closing issue.
