### ISSUE TITLE
Flags doesn't work as expected when using with a service

### ISSUE THREAD

**Issue by yarbelk** [micro/go-config#33]
Expectation - that flags work when running a service
Actuallity, the micro.Cli flag implementation overrides the built in flag and doesn't recognize your flags (this is obvious upon reflection).

what to do?

document when to use flag as a source? how to use it with  a service?

**Comment by asim** [comment]
The flag source is for the golang flag package. Please see the readme for the micro cli flags and source. https://github.com/micro/go-config/tree/master/source/microcli
