### ISSUE TITLE
Unable to load config from etcd 3

### ISSUE THREAD

**Issue by jlcrow** [micro/go-config#39]
We've attempted to use the etcd functionality in Load, but receive:

`error loading source etcd: source not found: /micro/config/`

We've added the following key as a test case to a local and remote etcd instance with same results:
etcd Version: 3.3.8
`etcdctl put micro/config/cache '{"address": "10.0.0.2", "port": 6379}'`
OK

```
etcdSource := etcd.NewSource(
	etcd.StripPrefix(true),
)
conf := config.NewConfig()
err := conf.Load(etcdSource)
fmt.Println(err)
```

**Comment by asim** [comment]
The key must be written as `etcdctl put /micro/config/cache`

**Comment by asim** [comment]
I've updated the readme to reflect this
