### ISSUE TITLE
source/reader encoder

### ISSUE THREAD

**Issue by dneves** [micro/go-config#44]
why is the reader always trying to convert configs to json?

is it possible to skip this step?  
also, is it possible to use something like a plaintext Encoder for the source / reader ?  

I'm trying to connect to a consul of mine which stores the key/value as plain text and i'm getting an error:
```
error loading source consul: error reading data: faild decode value. path: my/key.value, error: invalid character '%' looking for beginning of value
```

**Comment by asim** [comment]
If you'd like to read plain text you need to include a plain text encoder and specify that to the source.

The reason everything is converted to json is so that we have a single internal format to read from.
