### ISSUE TITLE
Get slice from env

### ISSUE THREAD

**Issue by e11it** [micro/go-config#47]
Hi!

Is it possible to get Slice value from env?

I set env `KAFKA_BROKERS="123"` and get nothing if this case:

```go
log.Println(conf.Get("kafka", "brokers").StringSlice([]string{}))
```

Output:

```
2018/09/04 22:38:29 []
```

And exception in this case

```go
type KafkaConfig struct {
	Brokers []string
	Topics []string
	GroupID string

}
...
cfg := new(Cfg)

conf.Scan(&cfg))
```

Exception:
```
json: cannot unmarshal string into Go struct field KafkaConfig.Brokers of type []string
```

**Comment by asim** [comment]
This is not currently supported. Environment variables can only be accessed as strings. Feel free to PR a change.

**Comment by flowchartsman** [comment]
This issue should be reopened, pending a proper resolution or PR
