### ISSUE TITLE
the second change by watch file source not effect

### ISSUE THREAD

**Issue by linger1216** [micro/go-config#58]
```
	err := config.Load(sourceList...)
	if err != nil {
		return err
	}

	// init watch
	watcher, err := config.Watch(watch)
	if err != nil {
		panic(err)
	}

	go func() {
		for {
			fmt.Println("next...")
			v, err := watcher.Next()
			fmt.Println("get...")
			if err == nil {
				obj := new(WatchConfig)
				v.Scan(obj)
				changeCallback(obj)
			}
		}
	}()
```

step1: change local config file  eg. level (debug -> info)
received change value

step2: change local config file again eg. level (info -> debug)
nothing...  not print get

please help me and checked . thanks.
(please forgive my poor english)

**Comment by asim** [comment]
How are you changing the file? There's a known issue with fsnotify (which we use) https://github.com/fsnotify/fsnotify/issues/17

**Comment by linger1216** [comment]
use textedit change

vscode first change value  [ok]
vscode second change value  [none happened]
vi first change value  [ok]
vi second change value  [none happened]


:(

**Comment by linger1216** [comment]
can you give me an example or use my demo code...

app.yaml
```
log:
  level: info
```

main.go
```
type _LogConfig struct {
	Level string `yaml:"level" json:"level" default:"debug"`
}

func main() {
	config.Load(
		file.NewSource(
			file.WithPath("/Users/lid.guan/Downloads/go_proc/src/learn_go/go-config/conf/app.yaml"),
		),
	)
	w, _ := config.Watch("log")
	conf := new(_LogConfig)
	go func() {
		for {
			v, err := w.Next()
			if err != nil {
				panic(err)
			}
			v.Scan(conf)
			fmt.Println(conf)
		}
	}()
	time.Sleep(time.Second * 100)
}
```

**Comment by asim** [comment]
Please read the linked issue. Text editors replace the file rather than contents of the file which means it's impossible to detect edits. You may be able to find some help in the linked issue to resolve this. Otherwise feel free to contribute to the file source to fix the issue. It's not our place to solve the underlying issue with how file changes are detected. We defer this to fsnotify.
