### ISSUE TITLE
go-cloud runtimevar uses driver.Watcher instead of runtimevar.Variable

### ISSUE THREAD

**Issue by vangent** [micro/go-config#65]
It looks like this code is using `driver.Watcher` directly. The intent is that users use `runtimevar.Variable` directly. In particular, there is no publicly exported way to create a `driver.Watcher`. For example, the `paramstore` [implementation](https://godoc.org/gocloud.dev/runtimevar/paramstore) returns a `runtimevar.Variable`.

**Comment by asim** [comment]
Ok thanks I'll take a look to replace later on today.

**Comment by vangent** [comment]
I am happy to send a PR for this as well, let me know.

**Comment by asim** [comment]
Thanks very much. Merged it.
