### ISSUE TITLE
Watching for a change in a JSON file on a non-object path attempts to deserialize value again

### ISSUE THREAD

**Issue by swedishborgie** [micro/go-config#73]
When creating a watcher for a configuration change as part of a JSON file specifying the path to an entry that is not an object causes the value to be treated as if it were JSON and re-run through the deserializer.

For instance, consider the following JSON configuration:

    {"hosts":
        {"database":
            {"address":"10.0.0.1","port": 3306}
        }
    }

Attach a watcher to the "address" path:

    w, err := config.Watch("hosts", "database", "address")

Change the address to anything else ("example.com" for instance) and save; the call to `w.Next()` will fail with the following error:

    invalid character 'e' looking for beginning of value

Switching the value to a JSON escaped string (e.g. "\"example.com\"") works. Watching the parent path (hosts.database) and reading into a struct works as expected as described in [the documentation](https://micro.mu/docs/go-config.html#watch-path).

Full example can be found [here](https://gist.github.com/swedishborgie/952971aed765153f2df97004aeb0fe21).

**Comment by asim** [comment]
Thanks for the detailed issue report. I've temporarily hacked this so it works. Although I'm hoping for a better longer term solution. https://github.com/micro/go-config/commit/e8c6a4c0ec05b7f08fadc966615358a43c4de630

**Comment by swedishborgie** [comment]
Thanks for the speedy reply and for the patch! I just tested the patch and can confirm this fixes the issue for me.

**Comment by asim** [comment]
Ok cool. Closing issue. It's a hack so I don't expect it to work for everything but someone else can help with a more elegant solution. My only other thought was to call config.Get rather than using the value returned by the watcher but this might be a race condition.
