### ISSUE TITLE
Unresolved package gocloud.dev@v0.9.0

### ISSUE THREAD

**Issue by igorrius** [micro/go-config#77]
Could you check package `gocloud.dev@v0.9.0` in `go.mod` file. Because there is a dns resolve error during a package update process.

**Error details:**
`gocloud.dev@v0.9.0: unrecognized import path "gocloud.dev" (https fetch: Get https://gocloud.dev?go-get=1: dial tcp: lookup gocloud.dev on 127.0.0.53:53: no such host)`

**Comment by asim** [comment]
It exists. Your local dns resolver is doing something strange.

```
$ dig gocloud.dev

; <<>> DiG 9.8.3-P1 <<>> gocloud.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 18942
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;gocloud.dev.			IN	A

;; ANSWER SECTION:
gocloud.dev.		3599	IN	A	185.199.108.153
gocloud.dev.		3599	IN	A	185.199.109.153
gocloud.dev.		3599	IN	A	185.199.110.153
gocloud.dev.		3599	IN	A	185.199.111.153

;; Query time: 33 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Feb  2 09:14:13 2019
;; MSG SIZE  rcvd: 93
```
