### ISSUE TITLE
Hi, watches currently keep firing error

### ISSUE THREAD

**Issue by AlexChenSkyBlue** [micro/go-config#83]
currently watches in configmap keep firing below error:
E0320 22:09:31.583293       1 reflector.go:126] github.com/micro/go-config/source/configmap/watcher.go:48: Failed to list *v1.ConfigMap: the server could not find the requested resource

Should replace watches:37 from configmap to configmaps.

**Comment by asim** [comment]
PR fix?

**Comment by XiangChen666** [comment]
does not seems like I have permission.

**Comment by asim** [comment]
Anyone can create pull requests.

**Comment by XiangChen666** [comment]
ERROR: Permission to micro/go-config.git denied to XiangChen666.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by asim** [comment]
Are you trying to push to the repo? That's not how this works. Fork the repo then make the change. Push that to your own account and then create a pull request against this repo

**Comment by XiangChen666** [comment]
just opened

**Comment by asim** [comment]
Merged.
